#!/bin/sh

#
# xinit startup
#

SYSTEM_XRESOURCES="/etc/X11/xinit/.Xresources"
SYSTEM_XMODMAP="/etc/X11/xinit/.Xmodmap"
SYSTEM_XINITRC_DIRECTORY="/etc/X11/xinit/xinitrc.d"

USER_XRESOURCES="$HOME/.config/X11/xinit/.Xresources"
USER_XMODMAP="$HOME/.config/X11/xinit/.Xmodmap"
USER_XINITRC_DIRECTORY="$HOME/.config/X11/xinit/xinitrc.d"

if [ -f "$SYSTEM_XRESOURCES" ]; then
    xrdb -merge "$SYSTEM_XRESOURCES"
fi

if [ -f "$SYSTEM_XMODMAP" ]; then
    xmodmap "$SYSTEM_XMODMAP"
fi

if [ -f "$USER_XRESOURCES" ]; then
    xrdb -merge "$USER_XRESOURCES"
fi

if [ -f "$USER_XMODMAP" ]; then
    xmodmap "$USER_XMODMAP"
fi

if [ -d "$SYSTEM_XINITRC_DIRECTORY" ] ; then
    for f in "$SYSTEM_XINITRC_DIRECTORY"/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done

    unset f
fi

if [ -d "$USER_XINITRC_DIRECTORY" ] ; then
    for f in "$USER_XINITRC_DIRECTORY"/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done

    unset f
fi

exec bspwm
