#! /bin/sh

#
# bspwm startup
#

BSPWMRC_DIRECTORY="$XDG_CONFIG_HOME/bspwm/bspwmrc.d"

if [ -d "$BSPWMRC_DIRECTORY" ] ; then
    for f in "$BSPWMRC_DIRECTORY"/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done

    unset f
fi

# Set wallpaper
feh --bg-fill ~/.wallpaper

# Set global settings
bspc config split_ratio 0.52
bspc config automatic_scheme longest_side
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
bspc config borderless_monocle true
bspc config gapless_monocle true

# Set node settings
bspc config border_width 0

# Set desktop settings
bspc config window_gap 32

# Set rules
bspc rule -a mpv state=floating sticky=on follow=off focus=on \
    rectangle=640x360+2760+1040
bspc rule -a "*:Toolkit:Picture-in-Picture" state=floating sticky=on \
    follow=off focus=on rectangle=640x360+2760+1040
bspc rule -a JDownloader state=floating center=true
bspc rule -a org.remmina.Remmina state=floating center=true
bspc rule -a Transmission-gtk state=floating center=true
bspc rule -a virt-manager state=floating center=true
bspc rule -a vlc state=floating center=true
